420 Add Numeric Rule and optional parameter to EmailRule
ONSdigital/ssdc-shared-sample-validation pull request #19
Opened 2022-10-03 08:48 UTC by AdamHawtin

# Motivation and Context

We want a Numeric characters rule which only allows digits. Also add an optional parameter to the email rule to allow for optional email columns.

# What has changed

- Add numeric rule and tests
- Add email rule optional parameter and tests

# How to test?

Checkout and build this branch, then build the branch of case processor and support tool and try defining/loading a sample with numeric columns and optional emails.

# Links

https://trello.com/c/4pMbQWfO/426-sample-generator-numeric-only-rule
https://trello.com/c/69XMsVj3/420-create-and-test-loading-a-cis-sample-file-3

2022-10-05 07:16 UTC, davidmort requested changes

2022-10-05 07:16 UTC, davidmort commented on src/main/java/uk/gov/ons/ssdc/common/validation/NumericRule.java
> +    if (data.matches("\\d*")) {
should this be `\\d+` to match 1 or more digits instead ```d*` which matches 0 or more digits?

2022-10-05 07:47 UTC, davidmort requested changes

2022-10-05 09:26 UTC, AdamHawtin commented on src/main/java/uk/gov/ons/ssdc/common/validation/NumericRule.java
> +    if (data.matches("\\d*")) {
This is something I was going to discuss in refinement of a tech session, we have rules that work in different ways where some define a column entirely, but some are to be combined with other rules, so for the `NumericRule` I was intending that it only checks that any characters in the data are digits, and would be combined with the `MandatoryRule` to make the value mandatory (and with length rules etc. to further specify).

I'm also going to add a ticket to flesh out some proper documentation of each rule, so these behaviours are explicitly documented.

2022-10-06 06:56 UTC, davidmort approved these changes

2022-10-06 13:22 UTC, merged